name: attendencetracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  salomon_bottom_bar: ^3.3.1
  loading_animation_widget: ^1.2.0+3
  http: ^1.1.0
  fluttertoast: ^8.2.2
  another_flushbar: ^1.12.30
  provider: ^6.0.5
  barcode_scan2: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
