name: attendencetracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  loading_animation_widget: ^1.2.0+3
  http: ^1.1.0
  another_flushbar: ^1.12.30
  provider: ^6.0.5
  barcode_scan2: ^4.2.4
  dot_navigation_bar: ^1.0.2
  intl: ^0.18.1
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
